### ISSUE TITLE
App should run in a Web Worker

### ISSUE THREAD

**Issue by jeffbcross** [angular/answers-app#12]
App will run in a web worker by default. 
- [x] Have app bootstrap from worker
- [x] WebWorker should play nice with Universal
- [ ] Make custom element wrapper for Material Design Lite lifecycle management
- [ ] Perhaps a wrapper for markdown editor (CC @robwormald)
- [ ] Make sure implementation works with popup or redirect authentication flow in #1 
- [ ] Add preboot library to app

**Comment by jteplitz** [comment]
I've gotten the app to bootstrap in a worker [here](https://github.com/jteplitz602/answers-app/tree/webworker), so this is now blocked until the [webworker router PR](https://github.com/angular/angular/pull/5932) lands.

**Comment by jeffbcross** [comment]
I added a task to include preboot as part of this issue

**Comment by jeffbcross** [comment]
Closed by ade67cf9b1acb6eefc4b7b718167fe6a5fce4a65
